apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  labels:
    app: sample-app-service
spec:
  selector:
    app: sample-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000